export const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "./src/assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "./src/assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "./src/assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 1,
    price: 22.0,
    img: "./src/assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Sweetener",
    category: 1,
    price: 59.9,
    img: "./src/assets/img/5.jpg",
    band: "Ariana Grande",
    year: 2018,
    id: 4,
  },
  {
    title: "Future Nostalgia",
    category: 1,
    price: 74.9,
    img: "./src/assets/img/6.jpg",
    band: "Dua Lipa",
    year: 2020,
    id: 5,
  },
  {
    title: "Selvagem?",
    category: 2,
    price: 42.5,
    img: "./src/assets/img/7.jpg",
    band: "Os Paralamas do Sucesso",
    year: 1986,
    id: 6,
  },
  {
    title: "O Descobridor dos Sete Mares",
    category: 2,
    price: 99.9,
    img: "./src/assets/img/8.jpg",
    band: "Tim Maia",
    year: 1983,
    id: 7,
  },
  {
    title: "Deixa Entrar",
    category: 3,
    price: 39.9,
    img: "./src/assets/img/9.jpg",
    band: "Falamansa",
    year: 2000,
    id: 8,
  },
  {
    title: "Essa É pra Vocês",
    category: 3,
    price: 49.9,
    img: "./src/assets/img/10.jpg",
    band: "Falamansa",
    year: 2001,
    id: 9,
  },
  {
    title: "Quadrilhas e Marchinhas Juninas",
    category: 3,
    price: 65.3,
    img: "./src/assets/img/11.jpg",
    band: "Luiz Gonzaga",
    year: 1965,
    id: 10,
  },
  {
    title: "Mais Feliz",
    category: 4,
    price: 19.9,
    img: "./src/assets/img/12.jpeg",
    band: "Zeca Pagodinho",
    year: 2019,
    id: 11,
  },
  {
    title: "Nos Arcos da Lapa",
    category: 4,
    price: 79.9,
    img: "./src/assets/img/13.jpg",
    band: "Péricles",
    year: 2013,
    id: 12,
  },
  {
    title: "Batuqueiro",
    category: 4,
    price: 38.45,
    img: "./src/assets/img/14.jpg",
    band: "Martinho da Vila",
    year: 1986,
    id: 13,
  },
  {
    title: "Sinatra & Tom Jobim",
    category: 5,
    price: 99.9,
    img: "./src/assets/img/15.jpeg",
    band: "Antonio Carlos Jobim",
    year: 1967,
    id: 14,
  },
  {
    title: "Elis & Tom",
    category: 5,
    price: 99.9,
    img: "./src/assets/img/16.png",
    band: "Antonio Carlos Jobim",
    year: 1974,
    id: 15,
  },
  {
    title: "Wave",
    category: 5,
    price: 99.9,
    img: "./src/assets/img/17.jpg",
    band: "Antonio Carlos Jobim",
    year: 1967,
    id: 16,
  },
  {
    title: "The Search",
    category: 6,
    price: 59.9,
    img: "./src/assets/img/18.png",
    band: "NF",
    year: 2019,
    id: 17,
  },
  {
    title: "Clouds",
    category: 6,
    price: 75.0,
    img: "./src/assets/img/19.jpg",
    band: "NF",
    year: 2021,
    id: 18,
  },
  {
    title: "N9na",
    category: 6,
    price: 45.0,
    img: "./src/assets/img/20.png",
    band: "Tech N9ne",
    year: 2019,
    id: 19,
  },
  {
    title: "Music to Be Murdered By",
    category: 7,
    price: 85.0,
    img: "./src/assets/img/21.png",
    band: "Eminem",
    year: 2020,
    id: 20,
  },
  {
    title: "Scorpion",
    category: 7,
    price: 47.9,
    img: "./src/assets/img/22.jpg",
    band: "Drake",
    year: 2018,
    id: 21,
  },
  {
    title: "Hollywood's Bleeding",
    category: 7,
    price: 78.0,
    img: "./src/assets/img/23.png",
    band: "Post Malone",
    year: 2019,
    id: 22,
  },
  {
    title: "Atlas",
    category: 8,
    price: 90.0,
    img: "./src/assets/img/24.jpg",
    band: "The Score",
    year: 2017,
    id: 23,
  },
  {
    title: "Moral Panic II",
    category: 8,
    price: 55.0,
    img: "./src/assets/img/25.jpg",
    band: "Nothing But Thieves",
    year: 2021,
    id: 24,
  },
  {
    title: "Unlimited Love",
    category: 8,
    price: 87.5,
    img: "./src/assets/img/26.jpg",
    band: "Red Hot Chili Peppers",
    year: 2022,
    id: 25,
  },
  {
    title: "Cachimbo da Paz",
    category: 9,
    price: 20.0,
    img: "./src/assets/img/27.jpg",
    band: "Gabriel, o Pensador",
    year: 1998,
    id: 26,
  },
  {
    title: "Folha de Bananeira",
    category: 9,
    price: 30.0,
    img: "./src/assets/img/28.jpg",
    band: "Armandinho",
    year: 2002,
    id: 27,
  },
  {
    title: "Bob Marley Greatest Hits",
    category: 9,
    price: 42.0,
    img: "./src/assets/img/29.jpg",
    band: "Bob Marley",
    year: 1992,
    id: 28,
  },
  {
    title: "If I Know Me",
    category: 10,
    price: 82.99,
    img: "./src/assets/img/30.png",
    band: "Morgan Wallen",
    year: 2018,
    id: 29,
  },
  {
    title: "On the Widow's Walk",
    category: 10,
    price: 65.4,
    img: "./src/assets/img/31.jpg",
    band: "The White Buffalo",
    year: 2020,
    id: 30,
  },
  {
    title: "Good Company",
    category: 10,
    price: 58.6,
    img: "./src/assets/img/32.jpg",
    band: "The Dead South",
    year: 2014,
    id: 31,
  },
  {
    title: "Uma Coisa",
    category: 11,
    price: 39.9,
    img: "./src/assets/img/33.jpg",
    band: "Morada",
    year: 2017,
    id: 32,
  },
  {
    title: "Rompendo a Barreira do Templo",
    category: 11,
    price: 45.5,
    img: "./src/assets/img/34.jpg",
    band: "Rodolfo Abrantes",
    year: 2012,
    id: 33,
  },
  {
    title: "Acoustic Worship, Vol. 7",
    category: 11,
    price: 28.9,
    img: "./src/assets/img/35.jpeg",
    band: "Will Morrison",
    year: 2020,
    id: 34,
  }
];

export const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Bossa-nova",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
